name: Update Followers Avatars

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all followers and update README
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          USERNAME="shardwiz"  # Replace with your GitHub username

          # Fetch all followers using pagination
          PAGE=1
          FOLLOWERS=""
          while true; do
            RESPONSE=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/users/shardwiz/followers?per_page=100&page=$PAGE")
            COUNT=$(echo "$RESPONSE" | jq '. | length')
            
            if [ "$COUNT" -eq 0 ]; then
              break
            fi
            
            FOLLOWERS+=$(echo "$RESPONSE" | jq -r '.[] | "<a href=\"\(.html_url)\" target=\"_blank\"><img style=\"border-radius: 50%; margin: 5px; border: 2px solid #ddd;\" src=\"\(.avatar_url)?s=40\" width=\"40\" height=\"40\" ></a>"' | tr '\n' ' ')
            PAGE=$((PAGE+1))
          done

          # Insert followers into README
          awk -v avatars="$FOLLOWERS" '
          BEGIN {RS=""; FS="<!-- FOLLOWERS START -->|<!-- FOLLOWERS END -->"}
          {print $1 " <!-- FOLLOWERS START --> <p align=\"center\">" avatars "</p> <!-- FOLLOWERS END --> " $3}
          ' README.md > temp.md
          
          mv temp.md README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "shardwiz"
          git config --global user.email "karlhanshegner@gmail.com"
          
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi
          
          git commit -m "Update followers' avatars"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
