name: Update Followers

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:  # Allows manual runs

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Fetch Followers and Update README
        run: |
          echo "Fetching all followers for shardwiz..."
          page=1
          > followers.json  # Empty file

          while :; do
            response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/users/shardwiz/followers?per_page=100&page=$page")

            # Debug: Print API response for troubleshooting
            echo "API Response: $response"

            # Check if API returned an error (instead of an array)
            if echo "$response" | jq -e 'type=="object"' >/dev/null; then
              echo "⚠️ GitHub API Error: $(echo $response | jq -r .message)"
              exit 1
            fi

            # Append valid followers to JSON file
            echo "$response" | jq '.[]' >> followers.json

            # Stop if no more followers are returned
            if [[ "$(echo $response | jq '. | length')" -eq 0 ]]; then
              break
            fi

            ((page++))
          done

          echo "Processing followers data..."
          jq -r '.[] | "<a href=\"" + .html_url + "\"><img src=\"" + .avatar_url + "\" width=\"50\" height=\"50\" style=\"border-radius: 50%;\"></a>"' followers.json > followers.md

          echo "Updating README.md..."
          awk '/<!-- FOLLOWERS_START -->/{print;print "";system("cat followers.md");print "";next} /<!-- FOLLOWERS_END -->/' README.md > temp.md && mv temp.md README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'shardwiz'
          git config --global user.email 'karlhanshegner@gmail.com'
          git add README.md
          git commit -m "Updated followers list" || exit 0
          git push
