name: Update Followers

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Followers and Update README
        run: |
          echo "Fetching all followers for shardwiz..."
          page=1
          > followers.json  # Create an empty file to store all followers
          
          while :; do
            response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/users/shardwiz/followers?per_page=100&page=$page")
              
            echo "$response" | jq -r '.[]' >> followers.json  # Append results

            # Check if the response is empty (no more followers)
            if [[ "$(echo $response | jq -r '. | length')" -eq 0 ]]; then
              break
            fi

            ((page++))
          done

          echo "Processing followers data..."
          cat followers.json | jq -r '.[] | "<a href=\"" + .html_url + "\"><img src=\"" + .avatar_url + "\" width=\"50\" height=\"50\" style=\"border-radius: 50%;\"></a>"' followers.json > followers.md

          echo "Updating README.md..."
          awk '/<!-- FOLLOWERS_START -->/{print;print "";system("cat followers.md");print "";next} /<!-- FOLLOWERS_END -->/' README.md > temp.md && mv temp.md README.md


      - name: Commit and Push Changes
        run: |
          git config --global user.name 'shardwiz'
          git config --global user.email 'karlhanshegner@gmail.com'
          git add README.md
          git commit -m "Updated followers list" || exit 0
          git push
